import type { ExperienceData } from '@/types/experience';

export const SEED_EXPERIENCES: ExperienceData[] = [
  {
    id: "exp-exp001",
    title: "Marine Drive Sunset Walk",
    category: "HIDDEN_GEMS",
    categoryLabel: "Hidden Enclaves",
    city: "Mumbai",
    area: "Marine Drive",
    priceMin: 0,
    priceMax: 0,
    durationMinutes: 90,
    ratingAverage: 4.86,
    authenticityRating: 0.94,
    candidateLat: 18.944497,
    candidateLng: 72.821025,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Marine_Drive_in_evening.JPG/1280px-Marine_Drive_in_evening.JPG"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Marine_Drive_in_evening.JPG/1280px-Marine_Drive_in_evening.JPG",
    description: "Marine Drive Sunset Walk located in Marine Drive, Mumbai. Best experienced during evening.",
    bestTime: "Evening",
    vibe: "Relaxing",
    tags: ["sunset", "sea", "walking"],
    humanTip: "Go around sunset but expect crowds on weekends",
  },
  {
    id: "exp-exp002",
    title: "Colaba Causeway Street Shopping",
    category: "SHOPPING",
    categoryLabel: "Artisan Shopping",
    city: "Mumbai",
    area: "Colaba",
    priceMin: 200,
    priceMax: 1500,
    durationMinutes: 150,
    ratingAverage: 4.83,
    authenticityRating: 0.95,
    candidateLat: 18.907583,
    candidateLng: 72.816661,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Colaba_Causeway%2CMumbai_-_panoramio.jpg/1280px-Colaba_Causeway%2CMumbai_-_panoramio.jpg"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Colaba_Causeway%2CMumbai_-_panoramio.jpg/1280px-Colaba_Causeway%2CMumbai_-_panoramio.jpg",
    description: "Colaba Causeway Street Shopping located in Colaba, Mumbai.",
    bestTime: "Afternoon",
    vibe: "Lively",
    tags: ["shopping", "street", "local"],
    humanTip: "Bargaining is part of the experience",
  },
  {
    id: "exp-exp003",
    title: "Kala Ghoda Art & Heritage Walk",
    category: "CULTURE",
    categoryLabel: "Cultural Heritage",
    city: "Mumbai",
    area: "Fort",
    priceMin: 0,
    priceMax: 0,
    durationMinutes: 120,
    ratingAverage: 4.85,
    authenticityRating: 0.93,
    candidateLat: 18.9287,
    candidateLng: 72.8331,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Jehangir_Art_Gallery%2C_Mumbai.jpg/1280px-Jehangir_Art_Gallery%2C_Mumbai.jpg"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Jehangir_Art_Gallery%2C_Mumbai.jpg/1280px-Jehangir_Art_Gallery%2C_Mumbai.jpg",
    description: "Heritage and gallery walk through the premier cultural precinct of Mumbai.",
    bestTime: "Morning",
    vibe: "Artistic",
    tags: ["art", "heritage", "galleries"],
    humanTip: "Don't miss Jehangir Art Gallery café.",
  },
  {
    id: "exp-exp004",
    title: "Girgaon Chowpatty Street Food Trail",
    category: "FOOD",
    categoryLabel: "Culinary Heritage",
    city: "Mumbai",
    area: "Girgaon",
    priceMin: 150,
    priceMax: 400,
    durationMinutes: 90,
    ratingAverage: 4.88,
    authenticityRating: 0.96,
    candidateLat: 18.9543,
    candidateLng: 72.8155,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Aran_Vada_Pav_Mumbai.jpg/1200px-Aran_Vada_Pav_Mumbai.jpg"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Aran_Vada_Pav_Mumbai.jpg/1200px-Aran_Vada_Pav_Mumbai.jpg",
    description: "Iconic beachside street food tasting pani puri, bhel puri, and kulfi.",
    bestTime: "Evening",
    vibe: "Bustling",
    tags: ["street-food", "beach", "chaat"],
    humanTip: "Pair the spicy sev puri with a cold malai kulfi.",
  },
  {
    id: "exp-exp005",
    title: "Bandra Pali Hill Café & Vintage Trail",
    category: "HIDDEN_GEMS",
    categoryLabel: "Hidden Enclaves",
    city: "Mumbai",
    area: "Bandra West",
    priceMin: 300,
    priceMax: 1200,
    durationMinutes: 120,
    ratingAverage: 4.82,
    authenticityRating: 0.91,
    candidateLat: 19.0626,
    candidateLng: 72.8295,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Bandra_Fort_View_Mumbai.jpg/1280px-Bandra_Fort_View_Mumbai.jpg"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Bandra_Fort_View_Mumbai.jpg/1280px-Bandra_Fort_View_Mumbai.jpg",
    description: "Quiet leafy bylanes, Portuguese bungalows, and boutique coffee houses.",
    bestTime: "Afternoon",
    vibe: "Bohemian",
    tags: ["cafes", "heritage", "bandra"],
    humanTip: "Best explored on foot or bicycle.",
  },
  {
    id: "exp-exp006",
    title: "Sassoon Docks Morning Auction",
    category: "CULTURE",
    categoryLabel: "Cultural Heritage",
    city: "Mumbai",
    area: "Colaba",
    priceMin: 0,
    priceMax: 0,
    durationMinutes: 90,
    ratingAverage: 4.89,
    authenticityRating: 0.98,
    candidateLat: 18.9167,
    candidateLng: 72.8250,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Fried_Bombil.jpg/1200px-Fried_Bombil.jpg"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Fried_Bombil.jpg/1200px-Fried_Bombil.jpg",
    description: "Witness the century-old Koli fishing community haul their daily catch at sunrise.",
    bestTime: "Sunrise",
    vibe: "Raw",
    tags: ["heritage", "fishing", "sunrise"],
    humanTip: "Wear waterproof shoes and arrive before 6:30 AM.",
  },
  {
    id: "exp-exp007",
    title: "Upvan Lake Twilight Promenade",
    category: "NATURE",
    categoryLabel: "Nature & Sanctuary",
    city: "Thane",
    area: "Upvan",
    priceMin: 0,
    priceMax: 0,
    durationMinutes: 75,
    ratingAverage: 4.79,
    authenticityRating: 0.91,
    candidateLat: 19.2244,
    candidateLng: 72.9608,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mumbai%2C_India%2C_Sunset_over_Haji_Ali_Dargah_Mosque.jpg/1280px-Mumbai%2C_India%2C_Sunset_over_Haji_Ali_Dargah_Mosque.jpg"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mumbai%2C_India%2C_Sunset_over_Haji_Ali_Dargah_Mosque.jpg/1280px-Mumbai%2C_India%2C_Sunset_over_Haji_Ali_Dargah_Mosque.jpg",
    description: "Scenic lakeside walkway nestled against the Yeoor Hills.",
    bestTime: "Sunset",
    vibe: "Serene",
    tags: ["lake", "walking", "nature"],
    humanTip: "Visit during the annual arts festival in winter.",
  },
  {
    id: "exp-exp008",
    title: "Parsik Hill Scenic Overlook",
    category: "NATURE",
    categoryLabel: "Nature & Sanctuary",
    city: "Navi Mumbai",
    area: "Belapur",
    priceMin: 0,
    priceMax: 0,
    durationMinutes: 60,
    ratingAverage: 4.75,
    authenticityRating: 0.89,
    candidateLat: 19.0145,
    candidateLng: 73.0421,
    mediaUrls: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Mumbai_03-2016_45_sunset_at_Marine_Drive.jpg/1280px-Mumbai_03-2016_45_sunset_at_Marine_Drive.jpg"
    ],
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Mumbai_03-2016_45_sunset_at_Marine_Drive.jpg/1280px-Mumbai_03-2016_45_sunset_at_Marine_Drive.jpg",
    description: "Panoramic hilltop viewpoint overlooking Navi Mumbai and Thane Creek.",
    bestTime: "Sunset",
    vibe: "Peaceful",
    tags: ["viewpoint", "nature", "hills"],
    humanTip: "Great breezy spot for twilight photography.",
  }
];
